//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using WCF.IBLL;
//删除模型和服务契约部分代码，引用服务端dll
namespace WCF.Model
{
    using System.Runtime.Serialization;
    
    
    
}




[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IUserInfoServiceChannel : IUserInfoService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class UserInfoServiceClient : System.ServiceModel.ClientBase<IUserInfoService>, IUserInfoService
{
    
    public UserInfoServiceClient()
    {
    }
    
    public UserInfoServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public UserInfoServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public UserInfoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public UserInfoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string GetName(int id)
    {
        return base.Channel.GetName(id);
    }
    
    //public System.Threading.Tasks.Task<string> GetNameAsync(int id)
    //{
    //    return base.Channel.GetNameAsync(id);
    //}
    
    public WCF.Model.UserInfo GetUserById(int id)
    {
        return base.Channel.GetUserById(id);
    }
    
    //public System.Threading.Tasks.Task<WCF.Model.UserInfo> GetUserByIdAsync(int id)
    //{
    //    return base.Channel.GetUserByIdAsync(id);
    //}
}
